import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";

const serif = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${serif.className}  antialiased`}>{children}</body>
    </html>
  );
}
